### ISSUE TITLE
Is Symfony 4 supported?

### ISSUE THREAD

**Issue by kubk** [BoShurik/TelegramBotBundle#10]
Hello, thanks for the bundle! I encountered a problem while installing your bundle for the symfony/skeleton project: https://github.com/symfony/skeleton

Steps to reproduce:
1) `composer create-project symfony/skeleton test`
2) `cd test`
3) `composer require boshurik/telegram-bot-bundle`

Here is the output:
```Using version ^2.3 for boshurik/telegram-bot-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing telegram-bot/api (v2.3.7): Loading from cache
  - Installing boshurik/telegram-bot-bundle (2.3.1): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 1 recipe (ad09ff1cd63feb8c60fc961551359110)
  - Configuring boshurik/telegram-bot-bundle (>=2.3.1): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 238:
!!                                                                               
!!    The child node "name" at path "boshurik_telegram_bot" must be configured.  
!!                                                                               
!!  
!!  
```

Can you explain please how to configure your bundle for Symfony 4?

**Comment by BoShurik** [comment]
There is no recipe for this bundle right now. You must configure it manually.
Create `config/packages/boshurik_telegram_bot.yaml` with [configuration](https://github.com/BoShurik/TelegramBotBundle#configuration)

**Comment by kubk** [comment]
Thanks for the response, now it works.
