### ISSUE TITLE
Bug in HelpCommand when Update has no Message

### ISSUE THREAD

**Issue by martcor** [BoShurik/TelegramBotBundle#15]
https://github.com/BoShurik/TelegramBotBundle/blob/4be962263120b8b400d8a0dd90a9b7e4ac18b5af/Telegram/Command/HelpCommand.php#L52

`Call to a member function getChat() on null`
Because there is not always a Message in the Update.

**Comment by BoShurik** [comment]
Can you elaborate? What should I send to reproduce error?

**Comment by BoShurik** [comment]
https://github.com/BoShurik/TelegramBotBundle/blob/master/Telegram/Command/AbstractCommand.php#L37 - `HelpCommand` is not applicable for empty messages

**Comment by martcor** [comment]
Ahh. I created my custom HelpCommand which always returned true. Nevermind
