### ISSUE TITLE
ngrok & TelegramBot

### ISSUE THREAD

**Issue by MyZik** [BoShurik/TelegramBotBundle#20]
Hi!

I'm using the bot example https://github.com/BoShurik/telegram-bot-example, it works with getUpdates but if trying to use webHooks bot doesn't give an answer. But all requests are successful:
![Bildschirmfoto 2019-11-04 um 14 14 18](https://user-images.githubusercontent.com/12817320/68123640-da155680-ff0d-11e9-9e33-02626ed8403e.png)

I think, that problem is in Symfony, something does not allow the webhook route and blocking him...

**Comment by BoShurik** [comment]
All my bots works fine with webhooks
Bot does not respond with `<html><body><h1>It works!</h1></body></html>`, looks like the problem on your side

**Comment by BoShurik** [comment]
Tried `ngrok` and it works.
[Previously](https://github.com/BoShurik/telegram-bot-example/commit/3530c6d8a881c20d5e920adf4db0257e70349061) webhook route was not configured in the example project. Did you add it manually?
