### ISSUE TITLE
Webhook UnsetCommand

### ISSUE THREAD

**Issue by cybernet** [BoShurik/TelegramBotBundle#23]
On Symfony 4.4 returns
`[info] User Deprecated: Return value of "BoShurik\TelegramBotBundle\Command\Webhook\UnsetCommand::execute()" should always be of the type int since Symfony 4.4, NULL returned.`

**Comment by BoShurik** [comment]
Thanks for the catch. Fixed in [4.0.1](https://github.com/BoShurik/TelegramBotBundle/releases/tag/4.0.1)
