### ISSUE TITLE
Only one commands works

### ISSUE THREAD

**Issue by polvanovvgosh** [BoShurik/TelegramBotBundle#27]
When I was practising writing bot telegrams, initially there were several commands and they worked as planned. After adding a command with steps, a problem arose. For any message, only the last command with steps is triggered.. Implementation as in the [bot example](https://github.com/BoShurik/telegram-bot-example/tree/master/src/Order/Telegram/Command) 
If I delete the command with steps, everything works fine.
Please tell me what could be the problem? 
Thanks for the help.

**Comment by BoShurik** [comment]
Please, provide your command's code

**Comment by polvanovvgosh** [comment]
https://pastebin.com/GATz88Ad

**Comment by BoShurik** [comment]
Is problem stays if you type `/frame cancel`? Looks like `$this->dailyframeHandler->hasdata` always returns `true`

**Comment by polvanovvgosh** [comment]
Thank you, you're right.
