### ISSUE TITLE
[Deprecation] Referencing controllers with a single colon is deprecated

### ISSUE THREAD

**Issue by MarStefo** [BoShurik/TelegramBotBundle#37]
Symfony 5.1.7 on PHP 7.4 report: `User Deprecated: Since symfony/http-kernel 5.1: Referencing controllers with a single colon is deprecated. Use "BoShurik\TelegramBotBundle\Controller\WebhookController::indexAction" instead.`

In prod mode it is simply given 404, while in dev it works cheerfully.

To solve, just edit: **src/Resources/config/routing.yml** line 4:

`        _controller: BoShurik\TelegramBotBundle\Controller\WebhookController:indexAction`
to
`        _controller: BoShurik\TelegramBotBundle\Controller\WebhookController::indexAction`

Thanks.

**Comment by BoShurik** [comment]
Hello, thank you for pointing to this issue. It's just a deprecation, it can't lead to an error. I just checked on [example project](https://github.com/BoShurik/telegram-bot-example) and it works fine

**Comment by BoShurik** [comment]
Fixed in 67feb46
