### ISSUE TITLE
webhook  с https не работает

### ISSUE THREAD

**Issue by usanjar** [BoShurik/TelegramBotBundle#40]
у меня установлена ssl сертификат на сервере, через консоль установил вебхук на адрес https://api.mysite.com/_telegram/secret-token и когда отправляю запрос на юрл вебхука почему-то запрос приходит по http и получаю 404. можете помочь?

**Comment by BoShurik** [comment]
Что выдает `bin/console telegram:webhook:info` ?

**Comment by usanjar** [comment]
![CleanShot 2021-12-08 at 21 56 47@2x](https://user-images.githubusercontent.com/13747950/145250397-0e9f8a75-592f-4da1-b096-0106e98aa855.png)


> Что выдает `bin/console telegram:webhook:info` ?

**Comment by usanjar** [comment]
остальные запросы без проблем работают по https

**Comment by BoShurik** [comment]
В `bin/console debug:router` этот роут присутствует?

**Comment by usanjar** [comment]
> В `bin/console debug:router` этот роут присутствует?

да есть

**Comment by usanjar** [comment]
![CleanShot 2021-12-08 at 22 08 51@2x](https://user-images.githubusercontent.com/13747950/145252326-b20b0f19-d9b9-4be6-bbfe-5ace26624854.png)

скрин ошибки

**Comment by usanjar** [comment]
закрываю issue, наверно серверу не понравился символ : в юрл из-за этого роут не нашелся.
