### ISSUE TITLE
Add support .php configs

### ISSUE THREAD

**Issue by des1roer** [BoShurik/TelegramBotBundle#47]
Symfony поддерживает конфиги вида
```
<?php

declare(strict_types=1);

use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

return static function (RoutingConfigurator $routingConfigurator): void {
    $routingConfigurator->import('@BoShurikTelegramBotBundle/Resources/config/routing.ym')
        ->prefix("/_telegram/%telegram_route_secret%");
};
```
а в коде захардкожен yaml

**Comment by BoShurik** [comment]
Почему это проблема?

**Comment by des1roer** [comment]
ErrorException: Cannot load resource "@BoShurikTelegramBotBundle/Resources/config/routing.ym". Make sure the "BoShurikTelegramBotBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@BoShurikTelegramBotBundle/Resources/config/routing.ym" is not empty. in /app/vendor/symfony/config/Loader/Loader.php:71

![image](https://user-images.githubusercontent.com/10970793/173004678-b0dc511f-168a-4ade-a1bb-81be5b88c9a0.png)

**Comment by des1roer** [comment]
поддерживается такой формат

```
        $container->import('../config/{packages}/*.{yaml,php}');
        $container->import('../config/{packages}/' . $this->environment . '/*.{yaml,php}');
        $container->import('../config/{services}.{yaml,php}');
        $container->import('../config/{services}_' . $this->environment . '*.{yaml,php}');
```

**Comment by BoShurik** [comment]
`routing.ym` - похоже на опечатку

**Comment by BoShurik** [comment]
Я так понял, проблема решена. Если что, то в будущем будет поддержка php конфигов (#44)
