### ISSUE TITLE
Inline Bot mention handling

### ISSUE THREAD

**Issue by drholera** [BoShurik/TelegramBotBundle#48]
Hey! Your work looks really amazing and very helpful, thank you! 

Have a question about the development of the inline bot. Is it possible to handle a simple mention of the bot with your stuff? After tagging the inline bot, `@myBotName`, I need to send messages. But unfortunately didn't find how to implement it.

**Comment by BoShurik** [comment]
Thank you!

Did not work with inline bots. Do you check https://core.telegram.org/bots/api#inline-mode and https://core.telegram.org/bots/api#getting-updates? Looks like you can use [Update::getInlineQuery](https://github.com/TelegramBot/Api/blob/master/src/Types/Update.php#L247) method

**Comment by drholera** [comment]
Thanks!
