### ISSUE TITLE
Example of adding a command

### ISSUE THREAD

**Issue by nimonimonimo** [BoShurik/TelegramBotBundle#5]
Hi,

Is there any chance you could show how to implement a custom command. I have tried to follow the documentation but as soon as I start to place command files in my own bundle and adds them to services.yml applications just dies.

Adding the provided /help-command works though. Now I just want to find a way to add a let's say /test-command that replies with "Hello world" I have the file but I can't manage to figure out how to reference in right without errors.

If you could give an example of this it would be very helpful.

**Comment by BoShurik** [comment]
What kind of errors did you get?

Here is example https://gist.github.com/BoShurik/05b609c248d77150af39f0620c8f4b4e

**Comment by BoShurik** [comment]
Here is an example project
https://github.com/BoShurik/telegram-bot-example

**Comment by nimonimonimo** [comment]
Thankyou very much!
