### ISSUE TITLE
How to disable built in `/help` command?

### ISSUE THREAD

**Issue by TrueXakeP** [BoShurik/TelegramBotBundle#56]
Hello.

I'm making a bot that should not have any commands (except `/start` but it is not exactly). It will be operated by buttons and keyboard.
How can I disable built in `/help` command? It implements the `PublicCommandInterface` and the `CommandInterface` so with `autoconfigure` enabled removing a `boshurik_telegram_bot.command` tag from config does't make any effect. `/help` is still there.
I'd like to keep `autoconfigure` enabled.

**Comment by BoShurik** [comment]
Hello. Are you trying to register every command from `vendor` directory? By default `autoconfigure` applied only to `src` directory so `/help` command should not be affected

**Comment by TrueXakeP** [comment]
Yes, sorry, I copied command from the example project.
