### ISSUE TITLE
При установке пишет ошибку

### ISSUE THREAD

**Issue by almazrt** [BoShurik/TelegramBotBundle#58]
PHP Fatal error:  Declaration of BoShurik\TelegramBotBundle\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder in /home/user1/projects/project1/vendor/boshurik/telegram-bot-bundle/DependencyInjection/Configuration.php on line 23

**Comment by BoShurik** [comment]
It's not tagged yet. Use `master` branch

**Comment by BoShurik** [comment]
6.0.0 is released
