### ISSUE TITLE
Support returning a response thru webhook

### ISSUE THREAD

**Issue by MrNicodemuz** [BoShurik/TelegramBotBundle#8]
Currently one cannot return a response directly when using the webhooks. This would be a nice feature to have.

**Comment by BoShurik** [comment]
What kind of response?
https://github.com/BoShurik/TelegramBotBundle/blob/master/Controller/WebhookController.php#L28 - this?

**Comment by MrNicodemuz** [comment]
Yes! Responses back to Telegram API, as described in here:
https://core.telegram.org/bots/api#making-requests-when-getting-updates

**Comment by BoShurik** [comment]
Done https://github.com/BoShurik/TelegramBotBundle/commit/78740cfc1b0e219fe7ecec46d333fed16601c88d
