### ISSUE TITLE
Error on Symfony 4

### ISSUE THREAD

**Issue by Gerben321** [BoShurik/TelegramBotBundle#9]
I'm trying this bundle, but when I want to initialize the $api like you do in your docs I get this error: 
`"The "bo_shurik_telegram_bot.api" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead."`.

Any idea what's wrong?

This is what I try:
```
/** @var TelegramBot\Api\BotApi $api */
$api = $this->container->get('bo_shurik_telegram_bot.api');
```

**Comment by BoShurik** [comment]
Hello! Can you check master branch? If problem is gone, I'll tag a release

**Comment by Gerben321** [comment]
Thanks, that solved it!

**Comment by BoShurik** [comment]
You can update to 2.3.1
